version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - yum update -y
      - yum install -y zip unzip git
      - amazon-linux-extras enable php8.2
      - yum clean metadata
      - yum install -y php php-cli php-mbstring php-pdo php-mysqlnd php-xml php-zip php-bcmath php-json
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - chmod +x /usr/local/bin/composer

  pre_build:
    commands:
      - php --version
      - composer --version
      - mkdir -p storage/framework/{cache,sessions,views}
      - mkdir -p storage/logs
      - chmod -R 755 storage bootstrap/cache

  build:
    commands:
      # Install dependencies first
      - composer install --no-dev --optimize-autoloader --no-interaction --no-progress
      
      # Create minimal .env file without using heredoc (to avoid YAML issues)
      - |
        if [ ! -f .env ]; then
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=" >> .env
        fi
      
      # Try to generate key only if .env exists
      - |
        if [ -f .env ]; then
          if ! grep -q '^APP_KEY=base64:' .env; then
            php artisan key:generate --force || echo "Key generation failed, continuing..."
          fi
        fi
      
      # Cache configurations
      - php artisan config:cache 2>/dev/null || true
      - php artisan route:cache 2>/dev/null || true
      - php artisan view:cache 2>/dev/null || true
      - php artisan optimize 2>/dev/null || true

  post_build:
    commands:
      # Create deployment zip (exclude .env file)
      - zip -r deployment.zip . \
          -x ".git/*" \
          -x ".github/*" \
          -x ".env" \
          -x "node_modules/*" \
          -x "tests/*" \
          -x "*.md" \
          -x "*.txt" \
          -x "storage/debugbar/*"
      
      # Show result
      - echo "Deployment package created:"
      - ls -lh deployment.zip

artifacts:
  files:
    - 'deployment.zip'
  discard-paths: yes

cache:
  paths:
    - 'vendor/**/*'
