version: 0.2

phases:
  install:
    commands:
      - echo "Installing Composer dependencies"
      - composer install --no-dev --optimize-autoloader

  build:
    commands:
      - echo "Build phase complete"

artifacts:
  files:
    - '**/*'
  discard-paths: no
