version: 0.2

phases:
  install:
    commands:
      - php -v
      - composer install --no-dev --optimize-autoloader

  build:
    commands:
      - php artisan config:clear || true
      - php artisan cache:clear || true

artifacts:
  files:
    - '**/*'
