version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      # Use Amazon Linux 2 default PHP (which might be 7.4)
      # Or let CodeBuild handle PHP installation via runtime-versions
      yum update -y
      yum install -y zip unzip git
      # PHP should already be installed via runtime-versions

  pre_build:
    commands:
      - echo "PHP version:"
      - php --version
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - chmod +x /usr/local/bin/composer
      - composer --version
      
      # Prepare Laravel
      - mkdir -p storage/framework/{cache,sessions,views}
      - chmod -R 755 storage bootstrap/cache

  build:
    commands:
      - composer install --no-dev --optimize-autoloader --no-interaction
      - php artisan key:generate --force
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  post_build:
    commands:
      # Simple zip creation
      - zip -r deployment.zip . -x "*.git*" "*.github*" "node_modules/*" "tests/*" "*.md" "*.txt" "storage/debugbar/*"
      - ls -lh deployment.zip

artifacts:
  files:
    - 'deployment.zip'
  discard-paths: yes
