version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      # For Amazon Linux 2023 (AL2023) - uses dnf instead of yum
      - dnf update -y
      - dnf install -y zip unzip git gcc-c++ make openssl-devel
      
      # Install PHP 8.2 and extensions
      - dnf install -y php php-cli php-common php-devel php-mbstring php-pdo php-mysqlnd php-xml php-gd php-opcache php-zip php-bcmath php-json php-intl
      
      # Install Composer
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - chmod +x /usr/local/bin/composer
      
      # Install Node.js 18.x
      - dnf install -y nodejs
      
      # Install jq for JSON parsing
      - dnf install -y jq

  pre_build:
    commands:
      # Display versions
      - echo "PHP version: $(php --version | head -1)"
      - echo "Composer version: $(composer --version)"
      - echo "Node version: $(node --version)"
      - echo "NPM version: $(npm --version)"
      
      # Create Laravel required directories
      - mkdir -p storage/framework/{cache,sessions,views}
      - mkdir -p storage/logs
      
      # Set permissions
      - chmod -R 755 storage bootstrap/cache
      - chown -R 1000:1000 storage bootstrap/cache

  build:
    commands:
      # Install dependencies with memory limit
      - php -d memory_limit=-1 /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction --no-progress
      
      # Handle environment configuration
      - if [ -f .env.example ] && [ ! -f .env ]; then cp .env.example .env; fi
      
      # Generate app key if needed
      - if [ -f .env ] && ! grep -q '^APP_KEY=base64:' .env; then php artisan key:generate --force; fi
      
      # Build assets if package.json exists
      - if [ -f package.json ]; then npm ci --silent; fi
      - if [ -f package.json ] && grep -q '"build"' package.json; then npm run build; fi
      
      # Cache configuration
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  post_build:
    commands:
      # Create deployment package
      - echo "Building Elastic Beanstalk deployment package..."
      - BUILD_ID=$(date +%Y%m%d-%H%M%S)
      
      # Create a clean deployment directory
      - rm -rf deploy && mkdir deploy
      
      # Use find and cp to copy files with exclusions
      - find . -type f -not -path "./node_modules/*" \
               -not -path "./vendor/*" \
               -not -path "./.git/*" \
               -not -path "./.idea/*" \
               -not -path "./storage/debugbar/*" \
               -not -path "./storage/logs/*" \
               -not -path "./storage/framework/cache/*" \
               -not -path "./storage/framework/sessions/*" \
               -not -path "./storage/framework/views/*" \
               -not -name "*.md" \
               -not -name "*.log" \
               -not -name ".env.example" \
               -not -name "phpunit.xml" \
               -not -name "docker-compose.yml" \
               -not -name "Dockerfile" | \
        while read file; do
          dest="deploy/$(dirname "$file")"
          mkdir -p "$dest"
          cp "$file" "$dest/"
        done
      
      # Ensure vendor and node_modules are copied
      - cp -r vendor deploy/ 2>/dev/null || true
      - cp -r node_modules deploy/ 2>/dev/null || true
      
      # Copy .ebextensions and .platform directories
      - [ -d .ebextensions ] && cp -r .ebextensions deploy/
      - [ -d .platform ] && cp -r .platform deploy/
      
      # Create a simple .ebignore
      - echo -e "node_modules/\nvendor/\n.git/\nstorage/debugbar/\n*.log" > deploy/.ebignore
      
      # Create the zip file
      - cd deploy && zip -qr "../laravel-deploy-${BUILD_ID}.zip" . && cd ..
      
      # Output artifact info
      - echo "Artifact: laravel-deploy-${BUILD_ID}.zip"
      - ls -lh "laravel-deploy-${BUILD_ID}.zip"

artifacts:
  files:
    - 'laravel-deploy-*.zip'
  name: laravel-deploy
  discard-paths: yes

cache:
  paths:
    - '/root/.composer/cache/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
