version: 0.2

phases:
  build:
    commands:
      - echo "Preparing Laravel package"
      - zip -r laravel-app.zip . -x "vendor/*" ".git/*" "node_modules/*"

artifacts:
  files:
    - laravel-app.zip
